#!/bin/sh

echo "CICD_GIT_REPO_NAME: ${CICD_GIT_REPO_NAME}"
echo "CICD_GIT_URL: ${CICD_GIT_URL}"
echo "CICD_GIT_COMMIT: ${CICD_GIT_COMMIT}"
echo "CICD_GIT_BRANCH: ${CICD_GIT_BRANCH}"
echo "CICD_GIT_REF: ${CICD_GIT_REF}"
echo "CICD_GIT_TAG: ${CICD_GIT_TAG}"
echo "CICD_EVENT: ${CICD_EVENT}"
echo "CICD_PIPELINE_ID: ${CICD_PIPELINE_ID}"
echo "CICD_EXECUTION_SEQUENCE: ${CICD_EXECUTION_SEQUENCE}"
echo "CICD_EXECUTION_ID: ${CICD_EXECUTION_ID}"
echo "CICD_REGISTRY: ${CICD_REGISTRY}"
echo "CICD_IMAGE: ${CICD_IMAGE}"
